export const API_URL = 'https://api.unsplash.com';
export const API_URL_PHOTOS = `${API_URL}/photos`;
export const API_URL_TOKEN = 'https://unsplash.com/oauth/token';
export const API_URL_AUTH = 'https://unsplash.com/oauth/authorize';
export const SECRET_KEY = 'atuMQh4C_aVVRAbu9qM89I5WPoZlttaoTIsaszGqnkA';
export const ACCESS_KEY = 't62lWQnP7JwrjwivGvTTEhqW3JDoslfIw74AnMrGyDQ';
export const REDIRECT_URI = 'https://gallery-lovat-theta.vercel.app/';
export const RESPONSE_TYPE = 'code';
export const SCOPE = 'public read_user read_photos write_likes';